### ISSUE TITLE
Possible solution regarding running scripts on location change

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#1]
`$nuxt.$router.afterEach` is a function that takes in a function that always runs after a route updates. This might be helpful?

**Comment by imadeanaccount1** [comment]
ooh! that seems really promising. i'll look into it, thank you!

**Comment by mybearworld** [comment]
I don't think this is a new addon...

**Comment by mybearworld** [comment]
I really don't understand extensions well enough, but it looks like `chrome.scripting.executeScript` allows you to pass in a function, which is probably helpful

**Comment by imadeanaccount1** [comment]
i might have a solution for this that I may test out soon, but i removed the new addon label 😊

**Comment by mybearworld** [comment]
> i might have a solution for this that I may test out soon

That's great! It's currently the reason I can't really use wasteof.plus when not testing addons...

**Comment by imadeanaccount1** [comment]
yeah, this is one of the last bugs i want to fix before making an "official" release and adding it to the Chrome/Edge/Opera Web Stores and the Firefox Addons Marketplace.
