### ISSUE TITLE
Poll icons appear multiple times

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#110]
![poll icons appearing three times](https://github.com/wasteofplus/wasteof.plus/assets/130385691/cec6743a-4820-42be-b044-949294b090f9)
I think the problem is that the post modal remains between route changes, which wasteof.plus doesn't expect. Ideally, there should be an option in the `addon.json` that would allow addon makers to choose whether to re-run on route changes.

**Comment by imadeanaccount1** [comment]
@mybearworld This issue can also be averted in the meantime by checking if the poll icon already exists and only injecting it if it does not (this is what the hovercards addon does atm). 

I do agree that a system for controlling how many times an addon is executed should be worked on, though. 👍
