### ISSUE TITLE
*Actually* format the code

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#24]
ESLint formats the JavaScript a little bit, but really not a lot and it also doesn't format other files (like the HTML files, [what is this formatting?!](https://github.com/imadeanaccount1/wasteof.plus/blob/7ff6b3346dbf0e6862cf3b0664ca4265a7718b8d/addons/profileHoverCards/templates/hovercard4.html)) Something like Prettier would probably help a lot further here

**Comment by imadeanaccount1** [comment]
@mybearworld Should ESLint continue to be used for JS liniting? I am in the process of deciding between using Prettier or Rome.

**Comment by mybearworld** [comment]
> @mybearworld Should ESLint continue to be used for JS linting? I am in the process of setting up Prettier.

I don't think there's much point to it.

**Comment by imadeanaccount1** [comment]
After I merge the newMessageNotifications addon, I will push an update adding Prettier. 👍

**Comment by imadeanaccount1** [comment]
@all-contributors please add @mybearworld for bug, ideas

**Comment by mybearworld** [comment]
@imadeanaccount1 Any progress on this?

**Comment by imadeanaccount1** [comment]
@mybearworld Ok, so I'm not done yet, but here's what I have so far (i decided to keep using ESLint for its linting and more advanced features while using prettier, which has its own benefits). #64

**Comment by mybearworld** [comment]
I'm not entirely sure why `*.js` is in the prettier ignore file? But yeah, it does.
