### ISSUE TITLE
Badges and polls don't show up when pages change

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#58]
It's another one of these :partying_face:

**Comment by imadeanaccount1** [comment]
Oh, okay, I know how to fix this now  at least 😅

**Comment by imadeanaccount1** [comment]
I need to test more, but I created a PR (#63) to fix this!

**Comment by imadeanaccount1** [comment]
@illogicalapple, @mybearworld this _might_ be fixed in [this action artifact](https://github.com/imadeanaccount1/wasteof.plus/actions/runs/5765634889) (emphasis on the italics). but i still gotta test, though!
