### ISSUE TITLE
Use actual TailwindCSS

### ISSUE THREAD

**Issue by mybearworld** [wasteofplus/wasteof.plus#8]
wasteof.plus is using some Tailwind classes, but these could break at any time if Jeffalo decided to update wasteof removing these classes, and it also sometimes uses CSS when it wouldn't really have to. I'd suggest wasteof.plus to actually use TailwindCSS instead of relying on it like this.

**Comment by imadeanaccount1** [comment]
hmm... idk really how to do this, but feel free to try! :)

**Comment by imadeanaccount1** [comment]
@mybearworld I think this will also be very useful for PR #10, which is the extension popup similar to ScratchAddons with addon settings/configurations. I have a very basic UI atm but tailwindcss would be very helpful.

**Comment by mybearworld** [comment]
> I'm really just stuck on how a logical way to call wasteof colors here - light mode colors and dark mode colors are slightly different, which makes it difficult to do in a sensible way.

I've figured this out, now I just need to wire things up properly

**Comment by imadeanaccount1** [comment]
@mybearworld that's really great, can't wait for that PR! :D

**Comment by mybearworld** [comment]
Is there anything wrong with the design of this?
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/93d2bd6d-e954-44df-8c3a-9a0e448ccedb)

**Comment by imadeanaccount1** [comment]
huh, that seems very strange... i have no idea what's wrong with it but I don't think it's work investigating given that I am currently in the process of replacing them with TailwindCSS toggles rather than my custom-designed (probably glitchy) ones. 😅

**Comment by mybearworld** [comment]
That's my Tailwind CSS rewrite thing

**Comment by imadeanaccount1** [comment]
is the first toggle fully disabled?

**Comment by mybearworld** [comment]
Yes, it is

**Comment by imadeanaccount1** [comment]
> I still have to sort out some colors/sizing/spacing.

Which I have now done!
![Screenshot 2023-07-18 144726](https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/e7767acf-743e-4197-aec8-35c7d74f9244)

**Comment by imadeanaccount1** [comment]
I was thinking that it would be better to use CSS too. I will close this, as I feel that it isn't really a necessary change for any currently-existing addons. If this becomes necessary in the future, we can reopen it, though 👍
