### ISSUE TITLE
CSS not working as intended on extension popup. (Lastest version of Chrome with W+ on Main branch.)

### ISSUE THREAD

**Issue by jakednolastname** [wasteofplus/wasteof.plus#85]
Some of the CSS works, most of it doesn't, I've seen in some screenshots what it's supposed to look like, but every version I've tried so far, the CSS doesn't work.

![image](https://github.com/imadeanaccount1/wasteof.plus/assets/122004617/790a9488-8fea-4df6-ba18-a0af6a802152)

**Comment by imadeanaccount1** [comment]
@jakednolastname The extension popup relies on dependencies (Tailwind CSS and Flowbite), so you have to run 'npm ci' in order to make the extension popup styles work :)

**Comment by imadeanaccount1** [comment]
Closing this because this has been reported/resolved before (and is related to dependency issues)

**Comment by jakednolastname** [comment]
> @jakednolastname The extension popup relies on dependencies (Tailwind CSS and Flowbite), so you have to run 'npm ci' in order to make the extension popup styles work :)

Ohhhhhh, I just imported the extension as an unpacked extension as is...
