### ISSUE TITLE
Idea: Append compatibility message to W+ specific post elements. 

### ISSUE THREAD

**Issue by jakednolastname** [wasteofplus/wasteof.plus#86]
I don't really know how to explain this, but much like most people do with the `<video>` tag, add a message that says something along the lines of, "You must download the Wasteof.plus extension and enable the [blah blah] addon to see this content.", with a link to Wasteof.plus' page and the addon name to enable, as not to confuse new users when they see the same random code floating around everywhere.

It would probably be the best if it would append the message after the post button was clicked, to keep the message intact.

**Comment by jakednolastname** [comment]
example:

`poll: ["yes","no"]
you must download a third party extension to view this content`

**Comment by imadeanaccount1** [comment]
@jakednolastname I'll think some more about how this would be best solved (as I think it could be kind of annoying to people who don't use wasteof.plus) 🤔

**Comment by imadeanaccount1** [comment]
closing this because i don't think this will be implemented
